controllers/admin.py
from flask import Blueprint
from flask import render_template, redirect, url_for, request
from model.models import * # to fetch all tables from .models
from sqlalchemy.exc import IntegrityError

admin = Blueprint("admin", __name__, template_folder="templates", static_folder="static")

@admin.route("/user_details/")
def user_details():
    query = request.args.get("search", "").strip() # Get the search query from URL
    if query:
        users = User.query.filter(
            (User.username.ilike(f"%{query}%"))|
            (User.password.ilike(f"%{query}%"))|
            (User.full_name.ilike(f"%{query}%"))|
            (User.email.ilike(f"%{query}%"))|
            (User.qualification.ilike(f"%{query}%"))
        ).filter_by(user_type="user").all()
    else:
        users = User.query.filter_by(user_type="user").all()
    
    reg_admin = User.query.filter_by(user_type="Admin").first_or_404()
    return render_template("user_details.html", users=users, reg_admin=reg_admin, query=query)

@admin.route("/admin_dashboard/")
def admin_dashboard():
    reg_admin = User.query.filter_by(user_type="Admin").first_or_404()
    query = request.args.get("search", "").strip() # Get the search query from URL
    if query:
        subjects = Subject.query.filter(Subject.subject_name.ilike(f"%{query}%")).all()
    else:
        subjects = Subject.query.all()
    
    return render_template("admin_dashboard.html", reg_admin=reg_admin, subjects=subjects, query=query)


# Subject Management - Create, Add, Update, Delete
@admin.route("/add_subject/", methods = ["GET", "POST"])
def add_subject():
    # if request.method == "GET":
    #     return render_template("add_subjects.html")
    if request.method == "POST":
        #handle the request
        try:
            new_subject = Subject(
                subject_name = request.form["subject_name"], #fetching name from subject form
                description = request.form["description"],  #fetching description from subject form
            )
        except IntegrityError:
            db.session.rollback()
        
        db.session.add(new_subject)
        db.session.commit()

        return redirect(url_for("admin.admin_dashboard"))

    return render_template("add_subjects.html")

@admin.route("/edit_subject/<int:subject_id>", methods = ["GET", "POST"])
def edit_subject(subject_id):
    subject = Subject.query.get(subject_id) # fetch subject by id

    if request.method == "POST":
        if subject:
            subject.subject_name = request.form.get("subject_name") #update name
            subject.description = request.form.get("description") #update description
            db.session.commit()
            return redirect(url_for("admin.admin_dashboard"))
        return redirect(url_for("admin.add_subject"))

    return render_template("edit_subjects.html", subject=subject)

@admin.route("/delete_subject/<int:subject_id>")
def delete_subject(subject_id):
    subject = Subject.query.get(subject_id) # fetch subject by id
    if subject:
        db.session.delete(subject)
        db.session.commit()
        return redirect(url_for("admin.admin_dashboard"))
    return "Subject not found", 404


#Chapter management - Create, Read, Update, Delete
@admin.route("/add_chapter/<int:subject_id>", methods = ["GET", "POST"])
def add_chapter(subject_id):
    subject = Subject.query.get(subject_id) # fetch subject id from subject table to connect with chapter

    if request.method == "POST":
        #handle the request
        try:
            new_chapter = Chapter(
                chapter_name = request.form["chapter_name"], #fetching name from chapter form
                description = request.form["description"],  #fetching description from chapter form
                subject_id = subject.subject_id
            )
        except IntegrityError:
            db.session.rollback()
        
        db.session.add(new_chapter)
        db.session.commit()

        return redirect(url_for("admin.admin_dashboard"))

    return render_template("add_chapters.html", subject=subject, subject_id=subject_id)

@admin.route("/edit_chapter/<int:chapter_id>", methods = ["GET", "POST"])
def edit_chapter(chapter_id):
    chapter = Chapter.query.get(chapter_id) # fetch subject by id

    if request.method == "POST":
        if chapter:
            chapter.chapter_name = request.form.get("chapter_name") #update name
            chapter.description = request.form.get("description") #update description
            db.session.commit()
            return redirect(url_for("admin.admin_dashboard"))
        return redirect(url_for("admin.add_chapter"))

    return render_template("edit_chapters.html", chapter=chapter)

@admin.route("/delete_chapter/<int:chapter_id>")
def delete_chapter(chapter_id):
    chapter = Chapter.query.get(chapter_id) # fetch subject by id
    if chapter:
        db.session.delete(chapter)
        db.session.commit()
        return redirect(url_for("admin.admin_dashboard"))
    return "Chapter not found", 404


#Quiz Management
@admin.route("/quiz_dashboard/")
def quiz_dashboard():
    reg_admin = User.query.filter_by(user_type="Admin").first_or_404()
    query = request.args.get("search", "").strip() # Get the search query from URL
    if query:
        quizzes = Quiz.query.filter(
            (Quiz.quiz_id.ilike(f"%{query}%"))|
            (Quiz.chapter_id.ilike(f"%{query}%"))|
            (Quiz.date_of_quiz.ilike(f"%{query}%"))|
            (Quiz.time_duration.ilike(f"%{query}%"))|
            (Quiz.remarks.ilike(f"%{query}%"))
        ).all()
    else:
        quizzes = Quiz.query.all()
    
    return render_template("quiz_dashboard.html", reg_admin=reg_admin, quizzes=quizzes, query=query)


@admin.route("/add_quiz/", methods = ["GET", "POST"])
def add_quiz():
    chapters = Chapter.query.all()

    if request.method == "POST":
        #handle the request
        try:
            new_quiz = Quiz(
                chapter_id = request.form["chapter_id"],
                date_of_quiz = datetime.strptime(request.form["date_of_quiz"], "%Y-%m-%d"),
                time_duration = request.form["time_duration"],
                remarks = request.form["remarks"],
            )

        except IntegrityError:
            db.session.rollback()

        db.session.add(new_quiz)
        db.session.commit()

        return redirect(url_for("admin.quiz_dashboard"))


    return render_template("add_quiz.html", chapters=chapters)

@admin.route("/edit_quiz/<int:quiz_id>", methods = ["GET", "POST"])
def edit_quiz(quiz_id):
    quiz = Quiz.query.get(quiz_id) # fetch quiz by id
    chapters = Chapter.query.all()

    if request.method == "POST":
        if quiz:
            quiz.chapter_id = request.form.get("chapter_id") #update chapter
            quiz.time_duration = request.form.get("time_duration") #update time of quiz
            quiz.date_of_quiz = datetime.strptime(request.form.get("date_of_quiz"), "%Y-%m-%d")  #update date of quiz
            quiz.remarks = request.form.get("remarks")
            db.session.commit()
            return redirect(url_for("admin.quiz_dashboard"))
        return redirect(url_for("admin.add_quiz"))

    return render_template("edit_quiz.html", quiz=quiz, chapters=chapters)

@admin.route("/delete_quiz/<int:quiz_id>")
def delete_quiz(quiz_id):
    quiz = Quiz.query.get(quiz_id)
    if quiz:
        db.session.delete(quiz)
        db.session.commit()
        return redirect(url_for("admin.quiz_dashboard"))
    return "Quiz doesn't exist", 404

#question management - Create, Read, Update, Delete
@admin.route("/add_question/<int:quiz_id>", methods = ["GET", "POST"])
def add_question(quiz_id):
    quiz = Quiz.query.get(quiz_id) # fetch quiz id from quiz table to connect with question

    if request.method == "POST":
        #handle the request
        try:
            new_question = Question(
                question_statement = request.form["question_statement"],
                question_title = request.form["question_title"],
                option1 = request.form["option1"],
                option2 = request.form["option2"],
                option3 = request.form["option3"],
                option4 = request.form["option4"],
                correct_answer = request.form["correct_answer"],
                quiz_id = quiz.quiz_id,
            )
        except IntegrityError:
            db.session.rollback()
        
        db.session.add(new_question)
        db.session.commit()

        return redirect(url_for("admin.quiz_dashboard"))
    
    return render_template("add_question.html", quiz=quiz, quiz_id=quiz_id)

@admin.route("/edit_question/<int:question_id>", methods = ["GET", "POST"])
def edit_question(question_id):
    question = Question.query.get(question_id) # fetch question by id

    if request.method == "POST":
        if question:
            question.question_statement = request.form.get("question_statement")
            question.question_title = request.form.get("question_title")
            question.option1 = request.form.get("option1")
            question.option2 = request.form.get("option2")
            question.option3 = request.form.get("option3")
            question.option4 = request.form.get("option4")
            question.correct_answer = request.form.get("correct_answer")
            db.session.commit()
            return redirect(url_for("admin.quiz_dashboard"))
        return redirect(url_for("admin.add_question"))

    return render_template("edit_question.html", question=question)

@admin.route("/delete_question/<int:question_id>")
def delete_question(question_id):
    question = Question.query.get(question_id) 
    if question:
        db.session.delete(question)
        db.session.commit()
        return redirect(url_for("admin.quiz_dashboard"))
    return "Question not found", 404

@admin.route("/delete_user/<int:user_id>")
def delete_user(user_id):
    user = User.query.get(user_id)
    if user:
        db.session.delete(user)

controllers/users.py
from flask import Blueprint
from flask import redirect, url_for, render_template, request, flash
from model.models import * # import all from models.py
from sqlalchemy.exc import IntegrityError
from datetime import datetime

app_user = Blueprint("app_user", __name__, template_folder="templates", static_folder="static")


@app_user.route("/login/", methods = ["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    elif request.method == "POST":
        #handle the request
        email = request.form.get("email") #fetching the email from form
        password = request.form.get("password") #fetching the password from form

        reg_user = User.query.filter_by(email=email).first() #filtering the users by its Email

        if reg_user:
            if reg_user.password == password:
                if reg_user.user_type == "Admin":
                    return redirect(url_for("admin.admin_dashboard")) # if the user is admin
                else:
                    return redirect(url_for("app_user.user_dashboard", user_id=reg_user.user_id)) # if any user wants to login
            else:
                flash("Email or Password is incorrect", "error") # for incorrect email or password
                return redirect(url_for("app_user.login"))
        else:
            flash("User does not exists", "error") # if an unregistered user wants to login
            return redirect(url_for("app_user.login"))
    else:
        return render_template("login.html") # if other than post request is applied
    

@app_user.route("/register/", methods = ["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    elif request.method == "POST":
        #handle request
        try:
            dob = request.form["dob"]
            dob_obj = datetime.strptime(dob, "%Y-%m-%d").date()
            new_user = User(
                username = request.form["username"],
                email = request.form["email"],
                password = request.form["password"],
                full_name = request.form["full_name"],
                qualification = request.form["qualification"],
                dob = dob_obj,
            )
        except IntegrityError:
            db.session.rollback()
            flash("User has already exists", "error")
            
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for("app_user.login"))


    return redirect(url_for("admin.admin_dashboard"))

# user dashboard of home screen
@app_user.route("/user_dashboard/<int:user_id>")
def user_dashboard(user_id):
    reg_user = User.query.filter_by(user_id=user_id).first_or_404()
    quizzes = Quiz.query.all()

    return render_template("user_dashboard.html", reg_user=reg_user, quizzes=quizzes)


# the quiz interface
@app_user.route("/user_dashboard/<int:user_id>/quiz/<int:quiz_id>", methods=["GET", "POST"])
def quiz(user_id,quiz_id):
    reg_user = User.query.get_or_404(user_id)
    quiz = Quiz.query.get_or_404(quiz_id)  # Fetch the quiz
    questions = quiz.questions # Fetch the specific question by its ID
    total = len(questions)

    if request.method == "POST":
        # Handle quiz submission
        total_score = 0
        for question in questions:
            selected_answer = request.form.get(f"question_{question.question_id}")
            if selected_answer == question.correct_answer:
                total_score += 1
        
        new_score = Score(user_id=user_id, quiz_id=quiz_id, total_scored=total_score)
        db.session.add(new_score)
        db.session.commit()

        return redirect(url_for("app_user.submit_quiz", user_id=user_id))

    return render_template("quiz.html", reg_user=reg_user, questions=questions, quiz=quiz, total=total)


@app_user.route("/user_dashboard/<int:user_id>/scoreboard")
def submit_quiz(user_id):
    reg_user = User.query.filter_by(user_id=user_id).first_or_404()
    scores = Score.query.filter_by(user_id=user_id).order_by(Score.time_stamp_of_attempt.desc()).all()
    
    return render_template(
        "submit_quiz.html",
        reg_user=reg_user,
        scores=scores
    )


#View the Quiz details
@app_user.route("/user_dashboard/<int:user_id>/view_quiz/<int:quiz_id>")
def view_quiz(user_id,quiz_id):
    quiz = Quiz.query.get(quiz_id) # fetch specific quiz by id
    reg_user = User.query.filter_by(user_id=user_id).first_or_404()

    return render_template("view_quiz.html", quiz=quiz, reg_user=reg_user)

templates/admin_dashboard.html
{% extends "layouts/boilerplate.html" %}

{% block navbar %}
    <div class="navbar navbar-expand-md bg-body-tertiary border-bottom sticky-top">
        <div class="container-fluid">
            <div class="navbar-nav">
                <a href="{{ url_for('admin.admin_dashboard') }}" class="nav-link btn btn-info"><strong><em>Home</em></strong></a>
                <a href="{{ url_for('admin.quiz_dashboard') }}" class="nav-link btn btn-info"><strong><em>Quiz</em></strong></a>
                <a href="{{ url_for('app_user.login') }}" class="nav-link btn btn-info"><strong><em>Logout</em></strong></a>
            </div>
            <div class="navbar-nav ms-auto">
                <form class="d-flex" role="search" action="{{ url_for('admin.admin_dashboard') }}" method="GET">
                  <input class="form-control me-2 search-inp" type="text" name="search" placeholder="Search Destinations" value="{{ query }}">
                  <button class="btn btn-search btn-success" type="submit">Search</button>
                </form>
            </div>
            <div class="navbar-nav ms-auto">
                <a href="{{ url_for('admin.user_details') }}" class="nav-link btn btn-info me-3"><strong><em>--USER DETAILS--</em></strong></a>
                <h3>Welcome {{ reg_admin.full_name }} </h3>
            </div> 
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row-g-3">
            <div class="col-6 offset-3">
                <h1 style="color: turquoise" class="mt-3 mb-3 col-6 offset-3">Welcome to the Admin Dashboard</h1>
                <div class="d-flex flex-wrap gap-3 justify-content-around">
                    {% for subject in subjects %}
                        <div class="card">
                            <div class="card-header bg-dark text-white text-center">
                                <strong><em>{{ subject.subject_name }}</em></strong>
                            </div>
                            <div class="card-body">
                                <table class="table table-striped mb-3 table-bordered">
                                    <tr class="table-primary">
                                        <th>Chapter Name</th>
                                        <th>No of questions</th>
                                        <th>Actions</th>
                                    </tr>
                                    {% for chapter in subject.chapters %}
                                        <tr>
                                            <td>{{chapter.chapter_name}}</td>
                                            <td> {{ chapter.quizzes | map(attribute='question_count') | sum }} </td>
                                            <td>
                                                <a href="{{url_for('admin.edit_chapter', chapter_id=chapter.chapter_id)}}" class="btn btn-success">Edit</a>
                                                <a href="{{url_for('admin.delete_chapter', chapter_id=chapter.chapter_id)}}" class="btn btn-success">Delete</a>
                                            </td>
                                    {% endfor %}
                                </table>
                                <a href="{{url_for('admin.add_chapter', subject_id=subject.subject_id)}}" class="btn btn-info mb-3 mt-3 ms-3">+ Chapter</a>
                                <a href="{{url_for('admin.edit_subject', subject_id=subject.subject_id)}}" class="btn btn-success">Edit Subject</a>
                                <a href="{{url_for('admin.delete_subject', subject_id=subject.subject_id)}}" class="btn btn-danger">Delete Subject</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a href="{{ url_for('admin.add_subject') }}" class="btn btn-info text-center mb-3 mt-3 col-6 offset-3">+ Add New Subject</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/edit_chapters.html
{% extends "layouts/boilerplate.html" %}

{% block content %}
    <div class="add-body row-g-3 mt-3">
        <div class="col-6 offset-3">
            <h2>Edit Chapter</h2>
            <form method="POST" action="{{ url_for('admin.edit_chapter', chapter_id=chapter.chapter_id) }}">
                <div class="mb-3 col-12">
                    <label for="chapter_name" class="form-label">Name:</label>
                    <input type="text" name="chapter_name" value="{{chapter.chapter_name}}" id="chapter_name" class="form-control" placeholder="Edit chapter">
                </div>
                <div class="mb-3 col-12">
                    <label for="description" class="form-label">Description:</label>
                    <textarea name="description" id="description" class="form-control" placeholder="Edit description">{{chapter.description}}</textarea>
                </div>
                <button type="submit" class="btn btn-success mt-3">Update</button>
                <a href="{{url_for('admin.admin_dashboard')}}" class="btn btn-success mt-3">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/edit_quiz.html
{% extends "layouts/boilerplate.html" %}

{% block content %}
    <div class="add-body row-g-3 mt-3">
        <div class="col-6 offset-3">
            <h2>Edit Quiz</h2>
            <form action="{{url_for('admin.edit_quiz', quiz_id=quiz.quiz_id)}}" method="POST">
                <div class="mb-3 col-12">
                    <label for="chapter_id" class="form-label">Chapter ID:</label>
                    <select name="chapter_id" id="chapter_id" class="form-control" placeholder="Enter the Chapter's ID">
                        <option selected>{{quiz.chapter.chapter_id}}</option>
                        <option disabled>Select a Chapter</option>
                        {% for chapter in chapters %}
                            <option value="{{chapter.chapter_id}}">{{chapter.chapter_id}} ({{chapter.chapter_name}}) </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3 col-12">
                    <label for="date_of_quiz" class="form-label">Quiz Date:</label>
                    <input type="date" name="date_of_quiz" value="{{quiz.date_of_quiz.strftime('%Y-%m-%d')}}" id="date_of_quiz" class="form-control" placeholder="dd/mm/yyyy">
                </div>
                <div class="mb-3 col-12">
                    <label for="time_duration" class="form-label">Quiz Duration:</label>
                    <input type="text" name="time_duration" value="{{quiz.time_duration}}" id="time_duration" class="form-control" placeholder="HH:MM">
                </div>
                <div class="mb-3 col-12">
                    <label for="remarks" class="form-label">Remarks:</label>
                    <textarea name="remarks" id="remarks" class="form-control">{{quiz.remarks}}</textarea>
                </div>
                <button type="submit" class="btn btn-success mt-3">Save</button>
                <a href="{{url_for('admin.quiz_dashboard')}}" class="btn btn-success mt-3">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/edit_subjects.html
{% extends "layouts/boilerplate.html" %}

{% block content %}
    <div class="add-body row-g-3 mt-3">
        <div class="col-6 offset-3">
            <h2>Edit Subject</h2>
            <form method="POST" action="{{ url_for('admin.edit_subject', subject_id=subject.subject_id) }}">
                <div class="mb-3 col-12">
                    <label for="subject_name" class="form-label">Name:</label>
                    <input type="text" name="subject_name" value="{{subject.subject_name}}" id="subject_name" class="form-control" placeholder="Edit Subject">
                </div>
                <div class="mb-3 col-12">
                    <label for="description" class="form-label">Description:</label>
                    <textarea name="description" id="description" class="form-control" placeholder="Edit description">{{subject.description}}</textarea>
                </div>
                <button type="submit" class="btn btn-success mt-3">Update</button>
                <a href="{{url_for('admin.admin_dashboard')}}" class="btn btn-success mt-3">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends "layouts/boilerplate.html" %}

{% block content %}
    <div class="form-body row-g-3 mt-3">
        <div class="col-6 offset-3">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-danger alert-dismissible fade show col-4 offset-8" role="alert">
                            <strong>{{message}}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <h2>Welcome to IntelliQuest</h2>
            <h3>Login</h3>
            <form action="{{ url_for('app_user.login') }}" method="POST">
                <div class="mb-3 col-12">
                    <label for="email" class="form-label">Email:</label>
                    <input type="text" name="email" id="email" class="form-control" placeholder="Enter your Email" required>
                </div>
                <div class="mb-3 col-12">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Enter your password" required>
                </div>
                <button type="submit" class="btn btn-success mt-3">Login</button>
            </form>
            <div class="d-flex align-items-center gap-2 mt-3 mb-3">
                <h3>Create new user?</h3> 
                <a href="{{ url_for('app_user.register') }}"><button type="submit" class="btn btn-primary">Register</button></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/quiz_dashboard.html
{% extends "layouts/boilerplate.html" %}

{% block navbar %}
    <div class="navbar navbar-expand-md bg-body-tertiary border-bottom sticky-top">
        <div class="container-fluid">
            <div class="navbar-nav">
                <a href="{{ url_for('admin.admin_dashboard') }}" class="nav-link btn btn-info"><strong><em>Home</em></strong></a>
                <a href="{{ url_for('admin.quiz_dashboard') }}" class="nav-link btn btn-info"><strong><em>Quiz</em></strong></a>
                <a href="{{ url_for('app_user.login') }}" class="nav-link btn btn-info"><strong><em>Logout</em></strong></a>
            </div>
            <div class="navbar-nav ms-auto">
                <form class="d-flex" role="search" action="{{ url_for('admin.quiz_dashboard') }}" method="GET">
                  <input class="form-control me-2 search-inp" type="text" name="search" placeholder="Search Destinations" value="{{ query }}">
                  <button class="btn btn-search btn-success" type="submit">Search</button>
                </form>
            </div>
            <div class="navbar-nav ms-auto">
                <a href="{{ url_for('admin.user_details') }}" class="nav-link btn btn-info me-3"><strong><em>--USER DETAILS--</em></strong></a>
                <h3>Welcome {{ reg_admin.full_name }} </h3>
            </div> 
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row-g-3">
            <div class="col-6 offset-3">
                <h1 style="color: turquoise" class="mt-3 mb-3 col-6 offset-3">Quiz Management</h1>
                <div class="d-flex flex-wrap gap-3 justify-content-around">
                    {% for quiz in quizzes %}
                        <div class="card">
                            <div class="card-header bg-info text-center text-white">
                                <div class="card-title">
                                    <strong><em>--Quiz{{quiz.quiz_id}}({{quiz.chapter.chapter_name}})--</em></strong>
                                </div>
                                <div class="card-subtitile">
                                    <strong><em>--{{quiz.chapter.subject.subject_name}}--</em></strong>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table table-striped table-bordered mb-3">
                                    <tr class="table-primary">
                                        <th>ID</th>
                                        <th>Q_Title</th>
                                        <th>Actions</th>
                                    </tr>
                                    {% for question in quiz.questions %}
                                        <tr>
                                            <td>{{question.question_id}}</td>
                                            <td>{{question.question_title}}</td>
                                            <td>
                                                <a href="{{url_for('admin.edit_question', question_id=question.question_id)}}" class="btn btn-success">Edit</a>
                                                <a href="{{url_for('admin.delete_question', question_id=question.question_id)}}" class="btn btn-danger">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                                <a href="{{url_for('admin.add_question', quiz_id=quiz.quiz_id)}}" class="btn btn-info mb-3 mt-3 ms-3">+ Questions</a>
                                <a href="{{url_for('admin.edit_quiz', quiz_id=quiz.quiz_id)}}" class="btn btn-success">Edit Quiz</a>
                                <a href="{{url_for('admin.delete_quiz', quiz_id=quiz.quiz_id)}}" class="btn btn-danger">Delete Quiz</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a href="{{url_for('admin.add_quiz')}}" class="btn btn-success text-center mb-3 mt-3 col-6 offset-3">+ New Quiz </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/user_dashboard.html
{% extends "layouts/boilerplate.html" %}

{% block navbar %}
    <div class="navbar navbar-expand-md bg-body-tertiary border-bottom sticky-top">
        <div class="container-fluid">
            <div class="navbar-nav">
                <a href="{{ url_for('app_user.user_dashboard', user_id = reg_user.user_id) }}" class="nav-link btn btn-info"><strong><em>Home</em></strong></a>
                <a href="{{ url_for('app_user.login') }}" class="nav-link btn btn-info"><strong><em>Logout</em></strong></a>
            </div>
            <div class="navbar-nav ms-auto">
                <a href="{{ url_for('app_user.submit_quiz', user_id = reg_user.user_id)}}" class="nav-link btn btn-info me-3"><strong><em>--SUMMARY--</em></strong></a>
                <h3>Welcome {{reg_user.full_name}}</h3>
            </div> 
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row-g-3">
            <div class="col-6 offset-3">
                <h2 class="mt-3 mb-3 col-6 offset-3" style="color: darkgoldenrod;">--Upcoming Quizzes--</h2>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered table-striped mb-3">
                            <tr class="table-primary">
                                <th>ID</th>
                                <th>No of Questions</th>
                                <th>Date</th>
                                <th>Duration(HH:MM)</th>
                                <th>Actions</th>
                            </tr>
                            {% for quiz in quizzes %}
                                <tr>
                                    <td>{{quiz.quiz_id}}</td>
                                    <td>{{quiz.questions | length}}</td>
                                    <td>{{quiz.date_of_quiz.strftime("%Y-%m-%d")}}</td>
                                    <td>{{quiz.time_duration}}</td>
                                    <td>
                                        <a href="{{url_for('app_user.view_quiz', user_id=reg_user.user_id, quiz_id=quiz.quiz_id)}}" class="btn btn-outline-info">View</a>
                                        <a href="{{url_for('app_user.quiz', user_id=reg_user.user_id, quiz_id=quiz.quiz_id)}}" class="btn btn-outline-success">Start</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}